name: x-Build Workflow template

on:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_URI:
        required: true
      AWS_ROLE_ARN:
        required: true
    outputs:
      image_tag:
        description: "The new docker image tag"
        value: ${{ jobs.build_and_push.outputs.image_tag }}

# Define environment variables used in the workflow.
env:
    AWS_REGION: us-east-1


# Permissions for the token
permissions:
  id-token: none
  contents: read

# Define the jobs in the workflow.
jobs: 
    # Job for building and pushing the Docker image.
    build_and_push:
      name: Build and Push to Docker Hub
      runs-on: ubuntu-24.04
      outputs:
        image_tag: ${{ steps.tag.outputs.image_tag }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 # https://github.com/actions/checkout

        - name: Setup Docker buildx
          uses: docker/setup-buildx-action@v3 # https://github.com/docker/setup-buildx-action

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 # https://github.com/aws-actions/configure-aws-credentials
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2 # https://github.com/aws-actions/amazon-ecr-login
    
        - name: Create Docker Image Tag
          id: tag
          run: |
            if [ -n "${GITHUB_REF_TYPE}" ] && [ "${GITHUB_REF_TYPE}" == "tag" ]; then
              echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            else
              echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
            fi

        - name: Build and push
          id: build
          uses: docker/build-push-action@v6 # https://github.com/docker/build-push-action
          with:
            context: .
            file: ./Dockerfile
            no-cache: true
            push: true
            attests: type=sbom
            platforms: linux/amd64,linux/arm64
            tags: ${{ secrets.DOCKER_REGISTRY_URI }}:${{ steps.tag.outputs.image_tag }}
